name: SonarCloud Analysis

on:
  # Trigger analysis when pushing to your main branches and with workflow_dispatch
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
  # Pull request analysis conditionally run with specific comment
  pull_request_target:  # Utiliser pull_request_target au lieu de pull_request
      types: [opened, synchronize, reopened]
  workflow_dispatch:  # Permet de lancer manuellement le workflow

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    # Pour pull_request_target, n'exécuter que pour les PR provenant de forks internes
    if: |
      (github.event_name == 'push') || 
      (github.event_name == 'workflow_dispatch') || 
      (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.owner.login == github.repository_owner)
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Récupère tout l'historique pour une meilleure analyse
          # Pour pull_request_target, checkout le code de la PR
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref || '' }}
          repository: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "temurin"
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nécessaire pour PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Détermine s'il s'agit d'une pull request ou non
          if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "pull_request_target" ]]; then
            # Pour les pull requests, ajoute les paramètres spécifiques pour l'analyse de PR
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Psonar \
              -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
              -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
              -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} \
              -Dsonar.pullrequest.github.repository=${{ github.repository }} \
              -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
          else
            # Pour les pushes normaux et les workflow manuels
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Psonar \
              -Dsonar.branch.name=${{ github.ref_name }}
          fi
